# [\ourblue PHI 631. Analytic Seminar]{.ourblue}

## [\ourblue Gödel’s Ontological Dreams and Explorations in Logic]{.ourblue}

::: {.column-body}
> *Die Welt ist vernünftig.*\
> — Gödel’s notebooks, “My Philosophical Outlook”[^gödel-1]
:::

[^gödel-1]: This is the first in a list of 14 propositions under the heading “My Philosophical Outlook” in Gödel’s notebooks. The last proposition is “Religions are, for the most part, bad—but religion is not.” Three of the remaining propositions are: (6) “There is incomparably more knowable *a priori* than is currently known”; (10) “Materialism is false”; and (13) “There is a scientific (exact) philosophy and theology, which deals with concepts of the highest abstractness; and this is also most highly fruitful for science”.

> *”My belief is theistic; not pantheistic, following Leibniz rather than Spinoza.*”\
> *”Spinoza’s God is less than a person. Mine is more than a person…. “*\
> — Gödel’s unsent response to the Grandjean questionnaire[^gödel-2]

[^gödel-2]: Quoted by Hao Wang, *Reflections on Kurt Gödel* (1987), 18 and *A Logical Journey: From Gödel to Philosophy* (1996), 152.

Kurt Friedrich Gödel (April 28, 1906 – January 14, 1978) was the greatest logician of the 20<sup>th</sup> century. Indeed, John von Neumann lauded him as the greatest “logician since Aristotle” and the only mathematician who was “absolutely irreplaceable”[^gödel-3][^gödel-4]. Harvard University bestowed upon him an honorary doctorate “for the discovery of the most significant mathematical truth of the century.”[^gödel-5] His friend Einstein said that he went to the Institute of Advanced Studies “*um das Privileg zu haben, mit Gödel zu Fuss nach Hause gehen zu dürfen.”*[^gödel-6] Despite this nearly universal admiration of Gödel,[^gödel-7] an accurate understanding of the scope and depth of Gödel’s achievements has been marred by misleading and exaggerated accounts.[^gödel-8] Gödel’s theorems, and philosophical achievements, however, stand in no need of exaggeration.

[^gödel-3]: These accolades are referenced in Karl Sigmund, John Dawson, and Kurt Mühlberger’s *Kurt Gödel: Das Album* (Vieweg & Sohn Verlag, April 2006), 10, which was published in conjunction with the Gödel exhibition at the 2006 Centenary sponsored by the Templeton Foundation at the University of Vienna.

[^gödel-4]: A tribute on the occasion of Gödel’s receiving an honorary doctorate from Harvard was authored by W. V. O. Quine. Gödel talked about this tribute with great admiration with his mother.

[^gödel-5]: That is, *“in order to have the privilege of walking home with Gödel”*, Oskar Morgenstern’s letter to Bruno Kreisky (*Bundesmeister fur Auswartige Angelegenheiten* of Austria) dated 23 October 1963.

[^gödel-6]: Two notable exceptions are Ludwig Wittgenstein and Ernest Zermelo, Gödel’s most famous philosophical and mathematical detractors. Although Wittgenstein and Gödel never met personally, each had views about the significance of the other’s work. Wittgenstein, for example, tried (unsuccessfully) to persuade Alan Turing of the insignificance of the paradoxes and metamathematics. Turing had already published his most celebrated result, the proof of the Unsolvability of the Halting Problem, which contains a philosophical analysis of computability, which Gödel praised highly. In the republication of his 1931 incompleteness results, Gödel added the following footnote in 1963: “In consequence of later advances, in particular of the fact that due to A. M. Turing’s work (Turing \[1937\] ‘On computable numbers, with an application to the *Entscheidungsproblem*,’ *Proceedings of the London Mathematical Society*, 2<sup>nd</sup> series, 42, 230-65) a precise and unquestionably adequate definition of the general notion of a formal system can be given, a complete general version of Theorems VI and XI is now possible. That is, it can be proved rigorously that in every consistent formal system that contains a certain amount of finitary number theory there exist undecidable arithmetic propositions and that, moreover, the consistency of any such system can be proved in the system.” Gödel met with Zermelo (DATES) and to tried to explain the fundamental ideas of his Incompleteness Theorem; however, Zermelo’s antipathy for Gödel’s theorems, never turned from *dustaub* into an intellectual acceptance (in contrast with Hilbert).

[^gödel-7]: John Cornwall’s *Darwin's Angel: an Angelic Riposte to* The God Delusion (Profile, 2007) contains the following common, but inaccurate, gloss on Gödel (64-65):

    > “The story begins in 1900 at the mathematical congress in Paris, where Hilbert set for the mathematicians of the world a list of problems for completion in the new century. Not least, he challenged them to demonstrate that mathematics is self-proving. He asked for a computational method, or algorithm, for resolving any kind of mathematical problem…. But in 1931 Kurt Gödel wrote a proof that upset Hilbert’s proposal. He demonstrated that there are mathematical statements that no conceivable computer, however capacious, could settle.
    >
    > “Crucially, philosophers of science have shown that what goes for mathematics goes for physics too.  Among early reactions to Hawking’s announcement of his quest for the Theory of Everything, a number of peer academics had attempted to expose the Gödel flaw in Hawking’s proposal. Gödel had shown, they insisted, that in principle, and for all time a Theory of Everything was bound to be either incomplete or inconsistent.  These included world-class mathematicians and theoretical physicists such as Roger Penrose of Oxford (author of *The Emperor’s New Mind*), Paul Davies… (author of *The Mind of God*), and … John Barrow (author of *Impossibility*).  ‘What Gödel shows,’ said Barrow, who now holds the chair in public understanding of mathematics in Cambridge, ‘is that no final theory of everything is possible; and that in any case there could be no algorithm, or mechanical procedure, that enables you to prove such a theory.”

    This account is tightly scripted, breath-taking in its sweep, but there is a problem. Practically every statement in this catechism is false or, at best, an exaggeration (see appendix).

[^gödel-8]: Leibniz (1646-1716) dreamed of a single logical calculus that could settle philosophical disputes; Frege (1848–1925) dreamed of discovering a logical calculus or *Begriffsschrift* (1879) that could serve as the foundation (*Grundlagen der Arithmetik*, 1884) from which the laws of arithmetic (*Grundgesetze der Arithmetik,* vol. I, 1893; vol. II, 1903) could be derived as theorems; and Cantor (1845-1918) dreamed of discovering the mathematics of infinity (*Contributions to the Founding of the Theory of Transfinite Numbers,* 1915). The first open problem listed by Hilbert in his famous 1900 lecture concerned Cantor’s Continuum Hypothesis, and Hilbert’s hopeful prediction (1926) was that “No one will drive us from the paradise which Cantor created for us.” Gödel’s theorems—the completeness of first-order logic, the incompleteness of axiomatic systems containing number theory, and the consistency of the Axiom of Choice and the Continuum Hypothesis with the other axioms of set theory—are not only the most strikingly original and profound foundational results in 20<sup>th</sup> century logic but these theorems had implications for each of these dreams

    Gödel’s Completeness Theorem proved that a formulation of the first-order part of Frege’s predicate logic was sound and sufficient to prove all the logical truths expressible in that formal language. Gödel’s celebrated Incompleteness Theorems showed that Leibniz’s dream was not only *unrealized* but, in principle, *unrealizable* within any single axiomatic system. And Gödel’s work in set theory concerning the consistency of the Axiom of Choice (1935) and Cantor’s Generalized Continuum Hypothesis (1939) proved these two axioms were relatively consistent with the remaining axioms of Zermelo-Fraenkel set theory, which characterizes, at least in part, Cantorian set theory.

Gödel dreamed of establishing significant philosophical theses with the rigour and precision of mathematics. Other great philosopher-mathematicians—Leibniz, Frege, and Cantor, for example—have also had grand dreams and Gödel’s theorems have had implications for those dreams.[^gödel-9]

[^gödel-9]: This felicitous phrase is due to Palle Yourgrau \[2019\], see also Wang \[1996\].

Despite their technical sophistication, Gödel’s theorems have perennially managed to escape mere mathematics and shed light on larger philosophical issues. While an undergraduate at the University of Vienna, Gödel determined to devote himself only to the sort of mathematics that would have broader philosophical implications. The reason why Gödel’s theorems achieved such significance is not merely his judicious choice of problems but his virtuosity with a new method of mathematizing philosophical problems. Hilbert’s challenge to solve open problems in the foundation of mathematics inaugurated the revolutionary shift from the Frege-Russell search for universal logics to metamathematics. Instead of remaining mired in unresolvable paradoxes, the [Gödel program]{.smallcaps}[^gödel-10] exploits the interplay between a formal and an informal intuition to obtain limitative results with mathematical precision.

[^gödel-10]: One reason why Gödel’s work is so widely misunderstood is that it has been accessed indirectly through highly simplified and misleading accounts. Nagel and Newman’s classic *Gödel’s Proof* \[1958, updated 2001\] included misstatements of Gödel’s first incompleteness theorem and Rosser’s improvement. Douglas Hofstader’s \[1979\] Pulitzer Prize-winning *Gödel, Escher Bach*, while popularizing Gödel’s ideas in a playful manner reminiscent of Lewis Carroll, isn’t a reliable guide because of Hofstader’s incessant pro-AI agenda woven into his exposition. Similar remarks, in the opposing view, might apply to Roger Penrose’s *anti*-AI agenda in *The Emperors New Mind* \[1989\] and *Shadows of the Mind* \[1994\]. Rebecca Goldstein \[2005\] deploys her considerable skills as a novelist and philosopher of science in *Incompleteness: The Proof and Paradox of Kurt Gödel*, but her accounts of foundational issues in mathematics are impressionistic and her overly dramatic insistence on Gödel’s unquestioned, and fanciful, platonism distorts what is known Gödel’s evolving views through his unpublished writings and conversations with Hao Wang \[1996\].

    More significantly, there is now a scholarly resource available in the monumental *Gödel’s Collected Works*, ed. Solomon Feferman, *et al.*, vols. I-V \[1982-2003\], which makes possible new avenues of research through an examination of the entire corpus of Gödel’s published and unpublished papers and lectures, Gödel’s *Nachlass* written in *Gabelsberger* shorthand script, and Gödel’s scientific correspondence sent and unsent—all with critical commentary by leading scholars.

Gödel’s achievement of producing logical elegant results by metamathematical methods that have implications for core philosophical problems—e.g., the reality of a Platonistic conceptual world, the non-algorithmic nature of the mind, the refutation of verificationism in mathematics, the structural similarities with completeness proofs and the ontological arguments, and the implications of relativity theory for the nature of time—ought to be more accurately and widely known, and deployed, by contemporary philosophers. This book addresses this need by providing an accessible, yet reliable, guide to Gödel’s logical explorations, philosophical ideas, and formal methodology.[^gödel-11]

[^gödel-11]: Donald Kalish (1919 – 2000) was my teacher and mentor at UCLA with whom I co-authored a second edition of the classic Kalish and Montague textbook. Kalish approached Alonzo Church to be my dissertation advisor at a critical time when I had no advisor. Donald (“Tony”) Martin read the first draft of my dissertation before it was submitted to Professor Church. The dissertation was subsequently submitted to Church at a time when he was recovering from a hall in a convalescent home in Santa Monica. I was the last student to have a dissertation directed by the great 20th century logician Alonzo Church, whose list of Ph.D. students reads like the “Who’s Who” of logic—among Church’s first twenty dissertation students are Stephen Kleene, J. Barkley Rosser, Alan Turing, Leon Henkin, John Kemeny, Martin Davis, Nicholas Rescher, William Boone, Hartley Rogers, Jr., Michael Rabin, Dana Scott, Simon Kochen, and Raymond Smullyan.

These are exciting times for Gödelian scholarship. Ever since the historic centenary celebration of Kurt Gödel’s birth, the *Horizons of Truth* conference in Vienna in 2006, which brought together philosophers, logicians, computer scientists and other scholars, the number of logicians, philosophers, and historians publishing topics related to Gödel’s life and research has grown dramatically.

Moreover, the topics in this explosion of research are no longer limited to Gödel’s recognized work in logic, set theory, the foundations of mathematics, but have expanded to encompass his explorations of the relativity physics of time travel, his views on computability and the philosophy of mind, and even his original contribution of a modal ontological argument to philosophical theology.

This explosion of research was facilitated by the scholarship published in *Gödel’s Collected Works* edited by Solomon Feferman, *et al.*, volumes I - V \[1982 - 2003\]. This monumental resource made new avenues of research possible by the carefully edited corpus of Gödel’s published and unpublished papers, lectures, and selected portions Gödel’s *Nachlass* written in *Gabelsberger* shorthand script, as well as much of Gödel’s scientific correspondence, sent and unsent—all with critical commentary by leading scholars.

It is perhaps not surprising that *Gödel’s Collected Works* is incomplete, e.g., Gödel’s correspondence with Georg Kreisel has been withheld from his correspondence as well as hundreds of pages of Gödel’s notebooks in *Gabelsberger* shorthand. At a recent conference *Gödel’s Legacy: Does the Future Lie in the Past?* \[July 2019\] dealing with Gödel’s writings on time and relativity, Jan von Plato gave a presentation about his project of translating from Gabelsberger short-hand Gödel’s four notebooks with the title “*Resultate Grundlagen*” consisting of 368 consecutively numbered pages and 90 theorems proved using a system of natural deduction invented by Gödel for this purpose.

The explorations in the chapters that follow represent some of my own attempts to contribute to the creative chaos in contemporary thinking about Gödel’s life, logical writings, and continuing legacy.

This book is written with several audiences in mind.

First, it is mean for students who loved their first course in symbolic logic and who want to grasp Gödel’s results in more than a metaphorical way. It is for students who have experienced the joy of constructing derivations and would like to understand Gödel’s theorems in ways that build upon what they already know. It is a guide that is simple and elegant, but not too simple with enough technical details (but not more than is necessary) to construct and comprehend those theorems.

Secondly, the book is meant for a general audience, who may appreciate the importance and power of logic but who are not satisfied with merely following logical proofs because they wish to explore the *philosophical* these ideas. It is also for those who want to know the *historical* narrative of Gottlob Frege’s *Begriffschrifft* \[1879\] conceptual writing or symbolic quantifier logic, Georg Cantor’s Transfinite Set Theory \[1874 – 1897\], the logical empiricism of the Vienna Circle (1924 – 1936), Bertrand Russell and Alfred North Whitehead’s *Principia Mathematica* \[1910-1913\], David Hilbert’s 23 open problems for 20<sup>th</sup> century mathematics, Gödel’s Completeness and Compactness Theorems \[1930\], Gödel’s Incompleteness Theorems \[1930\], Alonzo Church’s solution to Hilbert’s *Entscheidungsproblem* \[1936\], Alan Turing’s alternative solution, analysis of computability, and proof of the Unsolvability of the Halting Problem \[1936\], the friendship between Einstein and Gödel at the Institute for Advanced Studies in Princeton.

Thirdly, the book is also meant to continue the dialogue among Gödel amateurs and experts, who may never have thought of their areas of expertise in new ways or discovered connections between disciplines. The purpose of this book is not merely to *celebrate* Gödel’s achievements but to look at them in their historical context and as a coherent whole—suggesting certain ways of *comprehend* them … thinking and certain logical techniques that the used to tackle fundamental philosophical issues in the philosophy of mathematics.

The book is dedicated to my teachers, who taught me to love logic, and to my students who took all my classes and who still wanted to know more after the semesters ended. Among my teachers, first and foremost is Donald Kalish, my mentor at UCLA, but also Herbert Enderton, C. C. Chang, Tyler Burge, Donald (“Tony”) Martin, David Kaplan, and my Ph.D. chair Alonzo Church.[^gödel-12]

[^gödel-12]: I have used the Kalish-Montague-Mar natural deduction system to give advanced logic students a thread of Ariadne through Smullyan’s labyrinthine puzzles about logicians who reason about themselves in *Gödel’s Incompleteness Theorems* \[OUP, 1992\] and *Forever Undecided: A Puzzle Guide to Gödel* \[1987\].

I have also benefited from conversations and correspondence with friends and colleagues Matthias Baaz, John Dawson, Solomon Feferman, Juliet Floyd, Melvin Fitting, Thomas Graf, Patrick Grim, Jeffrey Heinz, Douglas Hofstader, Hans Kamp, Juliette Kennedy, Richard Larson, Robert L. Martin, Roger Penrose, Jan von Plato, Paul St. Denis, Nathan Salmon, Dana Scott, Brian Skyrms, Raymond Smullyan, Peter Woodruff, Palle Yourgrau, Yutong Zhang, and many others too numerous to mention.

My wish is that my teachers, colleagues, and students will continue to pursue their learning of logic and will pass on their love of logic and passion for philosophy to generations yet to come.

\renewcommand\labelitemi{}
### [\ourblue Chapter 1. Metalogic, Maximal Consistency, and Completeness]{.ourblue}

::: {.nobullet}
-   This chapter uses Lewis Carroll’s “What the Tortoise Taught Achilles” 1895\] to motivate the central questions of metalogic, the logic of logic. The natural deduction system of Kalish and Montague \[1964, 1982\] is reduced to Stanisław Leśniewski’s (1886–1939) Axiomatization for Conditional Logic. The symmetry between semantic and syntactic ideas motivates result s in proofs theory (e.g., the deduction theorem, proof of the independence of the axioms, the embedding of intuitionistic logic with classical logic) and model theory (e.g., soundness, completeness, compactness). It discusses why Gödel’s thought that logicians, blinded by the verificationism of the Vienna Circle, failed to formulate the question of completeness for first-order logic until nearly 50 years after Frege’s discovery. This chapter also explores unexpected consequences of Gödel‘s Compactness Theorem (e.g., Abraham Robinson’s calculus with infinitesimals), Gödel’s modal investigations into intuitionistic provability, and Gödel’s maximal consistency proof to provide proof of “Leibniz’s Lacuna”, the missing premise in Descartes’ version of the ontological argument.
:::

### [\ourblue Chapter 2. Gödel’s Incompleteness Theorems]{.ourblue}

::: {.nobullet}
-   This chapter presents Gödel’s Incompleteness Theorems \[1930\] using modal provability logic discovered by Löb, Kripke, de Jongh, and Sambin in the 1970s.[^gödel-13] This is done by developing the standard systems of modal logic **D, T, B, S4, S5** for the Kalish-and-Montague system of natural deduction. Gödel’s Incompleteness Theorems, especially, the Second Incompleteness Theorem, according to the usual story, destroyed Hilbert’s program, but Gödel’s writings show that he was quite sympathetic to the continuation of Hilbert’s program by other means. Gödel’s theorem shows the inadequacy of *single* formal system leaving open the possibility of “Ordinal logics” investigated by Turing \[1939\] in his thesis completed under Alonzo Church.[^gödel-14] Why doesn’t Gentzen’s \[1936\] Consistency Proof for Arithmetic contradict Gödel’s proof of the Unprovability of Consistency? Gödel’s last published paper his *Dialectica* interpretation \[1958\] extends Hilbert’s finitism with principles for functionals of finite type which can be used to prove the consistency of intuitionistic number theory.
:::

[^gödel-13]: This research program was renamed and revived in Feferman \[1962\] “Transfinite recursive progressions of axiomatic theories.” An accessible introduction is Franzén’s *Inexhaustibility* \[2004\].

[^gödel-14]: Philosophers have tried to sandbag Gödel’s ontological argument by adding additional premises to render it susceptible to standard atheistic objections, e.g., Howard Sobel \[1987\] claims that Gödel’s ontological argument implies a “modal collapse” by adding to Gödel’s argument the (implausible) premises that God must know all truths and that any truth that God knows must be necessary. For another instance, see “Truth, Omniscience, and Cantorian Arguments: An Exchange,” Alvin Plantinga and Patrick Grim \[1983\] and for a refutation of Grim, see Mar \[1993\], “Why Cantorian Arguments Against the Existence of God Don’t Work,” *IPQ*, 429-442.

### [\ourblue Chapter 3. Gödel vs. Turing: Mechanistic Algorithms or the Creative Mind?]{.ourblue}

::: {.nobullet}
-   This chapter explores the question whether Gödel’s platonist views in philosophy of mathematics can be reconciled with Turing’s mechanistic and computational views in the philosophy of mind. The self-appointed defenders of Gödel and Turing have tended to defend dichotomous views, e.g., materialist often give circular arguments for a mechanistic philosophy of mind, whereas J. R. Lucas’ “Mind, Machines and Gödel” \[1961\], John Searle’s \[1980\] provocative Chinese Room thought experiment, and Roger Penrose’s use of Gödel’s Second Incompleteness Theorem to argue against strong AI and for a quantum theory of consciousness presuppose, but provide a solution, to “hard problem” of consciousness. Gödel’s dichotomy is, in contrast, more nuanced: “*Either the human mind surpasses all machines (to be more precise: it can decide more number-theoretic questions than any machine) or else there exist number theoretic questions undecidable for the human mind.”* \[1951, Gibbs Lecture, Brown University\].
:::

### [\ourblue Chapter 4. Cantorian Set Theory, and the Gödel Program for Large Cardinal Axioms]{.ourblue}

::: {.nobullet}
-   This chapter examines Gödel’s profound contributions to axiomatic set theory. Gödel was not always the fundamentally convinced mathematical platonist of his three masterful philosophical articles “Russell’s Mathematical logic” \[1944\], “What is Cantor’s continuum problem?” \[1947, substantially updated 1964\], and his unpublished critiques of Rudolf Carnap’s (and the Vienna Circle’s) views on mathematics in “Is mathematics the syntax of language?” \[\*1953/9-III\]. In his 1933 Cambridge lecture Gödel expresses caution: ‘*The result… is that our axioms, if interpreted as meaningful statements, necessarily presuppose a kind of Platonism, which cannot satisfy any critical mind and which does not even produce the conviction that they are consistent.”* After 1959, Gödel’s turn the philosophy of Husserl indicates that he was searching for an epistemologically, or phenomenologically, grounded platonism.
:::

### [\ourblue Chapter 5. Gödel Universes and the Disappearance of Time]{.ourblue}

::: {.nobullet}
-   This chapter discusses Gödel’s discovery of a solution to Einstein’s field equations in the General Theory of Relativity of a cylindrical cosmological universe, which, like the self-referential Gödel sentence, rotates back on itself, thus allowing for time travel into the past by traveling into the future. The convergence of the physical with the philosophical was brought about by the convergence of two avenues of research—George Gamow’s question about the physics of cylindrical universes and Gödel’s antecedent philosophical interest in a Kantian theory of time. In contrast to his argument in the Incompleteness Theorems in which Gödel affirms the intuitive notion of truth to establish the incompleteness of provability within formal arithmetic, Gödel uses the physics of cosmological universes with close time-like circles to call into question the reality of our intuitive (“A series”) conception of time.
:::

### [\ourblue Chapter 6. Gödel’s Citizenship Test and a “Strange Loop” in the U.S. Constitution]{.ourblue}

::: {.nobullet}
-   Naively, we assume a democratic society automatically results from “majority rule” based on the principle of “one person one vote.” These assumptions about voting are demonstrably false. Recent elections have produced widespread disillusionment with democratic processes, which appear to be “rigged.” Voter alienation can be blamed on many different factors, e.g., the two-party system, the electoral college, echo chambers of slanted reporting, disinformation through foreign interference, gerrymandering, voter suppression, etc. However, there are also paradoxes hidden within the logic of different methods of vote counting. This chapter discusses voting paradoxes, Arrow’s Theorem about the Impossibility of Democracy, and Gödel’s discovery of an “inconsistency” in the U. S. Constitution that would allow for a democracy to end up with a dictatorship.
:::

### [\ourblue Chapter 7. Gödel’s GOD: Modal Monstrosity or Logical Investigation of a Leibnizian Lacuna?]{.ourblue}

::: {.nobullet}
-   On February 10<sup>th</sup>, 1970, when he feared his own death, Gödel shared his notes for an ontological proof for the existence of God with Dana Scott—two pages of symbolic formulas with terse, sometimes cryptic, comments. Gödel did not try to prove, as Leibniz did, that perfections are mutually compatible.[^gödel-15] Instead he instead postulates that positive properties are closed under conjunction and that the property of positiveness is monotonic. This advances the literature, not by deriving God’s actual existence from God’s possible existence,\[\^16\] but by axiomatizing relevant notions and constructing a modal maximality argument. Since Gödel never published his argument, there has arisen a philosophical and logical tradition of proposing emendations to Gödel’s argument. Scott himself circulated a modified version of Gödel’s argument with brief notes on his conversation with Gödel (Scott, 1987). Howard Sobel (1987) published his transcription from Gödel’s original handwritten notes together with his charge that it was implicated in a “modal collapse.” Responding to Sobel’s charge, Anderson \[1990\] set forth an elegant set of emendations. More recently, Christoph Benzmüller with Bruno Woltzenlogel Paleo and others \[2014\] have published computational studies of Gödel’s modal ontological argument.
:::

[^gödel-15]: Robert M. Adams \[1971\] “*The Logical Structure of Anselm’s Argument“, Philosophical Review* 80:647-84 pointed out that G follows from the premise $\Box(G\to\Box G)$, the modal axiom $\mathbb{B}\,\,\Box G\to\Box\Box G$, and the possibility premise $\Box G$.

\renewcommand\labelitemi{\labelitemito}

```{=html}
<!-- [**\
**]{.smallcaps} -->
```
## [\ourblue Appendix]{.ourblue}
[\ourblue **Gödel’s Theorem: An Incomplete Guide to Its Use and Abuse** by Torkel Franzén]{.ourblue}  
A K. Peters, Wellesley, Massachusetts, 2005), 172 pages, ISBN 1-56881-238-8, \$24.95.

----

Reviewed by Gary Mar, *The Mathematical Intelligencer* (vol. 29, no. 2), 2007, pp. 66-70.

At the Gödel Centenary Conference, “Horizons of Truth”, held at the University of Vienna in April 2006, Solomon Feferman paid tribute to the work of the late Torkel Franzén. Feferman’s comments, printed on the cover of *Gödel’s Theorem: An Incomplete Guide to Its Use and Abuse*, succinctly pinpoints Franzén’s distinctive achievement. “This unique exposition of Kurt Gödel’s stunning incompleteness theorems for a general audience manages to do what none other has accomplished; explain clearly and thoroughly just what the theorems really say and imply and correct their diverse misapplications to philosophy, psychology, physics, theology, post-modernist criticism and what have you.”

Franzén’s book will be of interest to three audiences: (1) beginning logic students who want a concise and self-contained explanation of what Gödel’s theorems *do* say; (2) non-mathematically trained scholars and educated laypersons who want a logically correct explanation of Gödel’s theorems do *not* say; and (3) professional logicians who want a comprehensive, and critical, survey of the philosophical perspectives opened up by Gödel’s work.

Logic students now have access to many popular accounts of Gödel’s life and work—Nagel and Newman’s classic exposition *Gödel’s Proof* (1959) and Douglas Hofstader’s Pulitzer-Prize winning *Gödel, Escher Bach* (1979), and more recently, John Casti and Werner DePauli’s *Gödel: A Life of Logic* (2000) based on the Austrian national television documentary and Rebecca Goldstein’s novelistic biography *Incompleteness: The Proof and Paradox of Kurt Gödel* (2005). However, these books tend to sacrifice technical correctness for public comprehensibility. None of these books comment in detail on the many misstatements and misapplications of Gödel’s theorem, and some commit the very errors Franzén exposes. Steering the beginning student clear of some common confusions, Franzén explains technical terms and poses instructive questions:

-   Gödel published the *completeness* theorem (1930) for his doctoral dissertation and then in the following year published his celebrated *incompleteness* theorem (1931). The latter is not the negation of the former. What are the two quite distinct meanings of *completeness* in these two landmark theorems by Gödel—the former concerning first-order logic and the latter concerning Peano arithmetic?

-   Although it is common to speak of *the* incompleteness theorem, there are actually *two* incompleteness theorems, known as Gödel’s First and Second Incompleteness Theorems. Contemporary formulations of both theorems talk about formal systems that “contain a certain amount of arithmetic.” What two different requirements are meant by this single phrase?

-   One important simplification of Gödel’s first incompleteness theorem was discovered by J. Barkley Rosser (1936). What is the difference between Rosser’s notion of *simple consistency* and Gödel’s original formulation of his first completeness theorem in terms of *ω-consistency*? Goldbach’s famous unproven conjecture is that every even number greater than 2 is the sum of two primes. How is Rosser’s simplification related to the fact that Goldbach-like statements (i.e., statements with the same logical form as Goldbach’s conjecture, known as Π-0-1 statements) that are undecidable must be true?

-   Gödel’s incompleteness theorem, contrary to some misstatements, does not imply that *every* consistent formal system is incomplete. The Theory of Real Numbers, for example, is complete. How is this possible since the Real Numbers include the Natural Numbers of arithmetic? Moreover, certain subtheories of Peano Arithmetic, such as Presberger Arithmetic (1928), are decidable.

-   Four years after the publication of Gödel’s incompleteness results, Gerhard Gentzen (1935) published a proof of the consistency of elementary arithmetic making use of a generalized version of mathematical induction, known as transfinite induction. Why doesn’t Gentzen’s result conflict with Gödel’s Second Incompleteness Theorem, which concerns the unprovability of consistency for a wide spectrum of formal systems?

Chapter 2, “The Incompleteness Theorem: An Overview,” introduces the reader to the First Incompleteness Theorem, its relation to Hilbert’s *Non Ignorabimus* view of mathematics, and its irrelevance with regard to explaining the “Postmodern condition.” Chapter 3, “Computability, Formal Systems, and Incompleteness,” explains the conceptual connections among the logical notions of computability, formal systems, and incompleteness. These initial chapters of Franzén’s book, then, give the beginning logic student a correct and concise account of what the Gödel incompleteness theorems actually *do* say.

$$\cdots$$

Readers who are non-mathematically-inclined but intrigued by the many claims about the implications of Gödel’s work will find Franzén a sober and reliable guide in explaining what Gödel’s theorems do *not* say. For example, does Gödel’s theorem show that a Theory of Everything (TOE) in theoretical physics is impossible? Do Gödel’s theorems refute the strong Artificial Intelligence (AI) thesis that the human mind can be modeled by a computer? “No mathematical theorem,” Franzén notes, “has aroused so much interest among nonmathematicians as Gödel’s incompleteness theorem.” Indeed, Franzén’s book grew out of taking on the exhausting task of commenting on the seemingly inexhaustible erroneous references on the internet to Gödel’s incompleteness theorems.

Franzén discusses misuses of the incompleteness theorems in theoretical physics and theology (Chapter 4), in skeptical arguments about mathematical knowledge (Chapter 5), and in the Lucas-Penrose arguments about the limitations of Artificial Intelligence (Chapter 6). He dispatches his task with great clarity and a little self-reflexive humor. After acknowledging his colleagues in the preface, Franzén drolly comments: “For any remaining instances of incompleteness or inconsistency in the book, I consider myself entirely blameless, since after all, Gödel proved that any book on the incompleteness theorem must be incomplete or inconsistent. Well, maybe not.”

“Gödel’s theorem is an inexhaustible source of intellectual abuses,” note Alan Sokel and Jean Briemont in *Fashionable Nonsense: Postmodern Intellectuals’ Abuse of Science* (1997), which is based on the famous hoax in which Sokel submitted a parody of a postmodern article that was accepted for publication. Had Franzén limited his sites to debunking postmodern, political or poetic invocations of Gödel’s theorem that were “obviously nonsensical,” this book could easily have settled into a smugness that comes from dispatching strawmen arguments.

Franzén aims higher. Even competent commentators have erred in misleading the public. Franzén, for example, criticizes Nagel and Newman for claiming that Gödel proves “that it is impossible to establish the internal logical consistency of a very large class of deductive systems—elementary arithmetic, for example—unless one adopts principles of reasoning so complex that their internal consistency is as open to doubt as that of the systems themselves.” Franzén criticizes Freeman Dyson and Stephen Hawking for invoking Gödel’s theorem in their skeptical arguments against the possibility of a Theory of Everything (TOE). Gregory Chaitin, widely acknowledged for his information-theoretic interpretation of Gödel’s theorem, is still taken to task for this misleading metaphor*: “Stated in terms of information theory, Gödel’s theorem says that a 100 pound theorem cannot be derived from 10 pound axioms.”* Let us consider these criticisms in more detail.

In Chapter 4 Franzén discusses the claim that, because of Gödel’s theorem, the physicist’s dream of a Theory of Everything is not only unattained, but theoretically unattainable. In “The World on the String” in the *New York Review of Books* (2004), Freeman Dyson argued: “Another reason why I believe science to be inexhaustible is Gödel’s theorem…. His theorem implies that pure mathematics is inexhaustible. No matter how many problems we solve, there will always be other problems that cannot be solved within the existing rules. Now I claim that because of Gödel’s theorem, physics is inexhaustible too.” In his talk “Gödel and the End of Physics,” Stephen Hawking has argued similarly: “In the standard positivist approach to the philosophy of science, physical theories live rent-free in a Platonic heaven of ideal mathematical models… But we are not angels who view the universe from the outside. Instead, we and our models are both part of the universe we are describing. Thus, a physical theory is self-referencing, like in Gödel’s theorem. One might therefore expect it to be either inconsistent or incomplete.”

Do Gödel’s theorems have such universal implications? Drawing on Feferman’s reply to Dyson in the *New York Review of Books* ([www.nybooks.com/articles/17249](http://www.nybooks.com/articles/17249)), Franzén explains: *“The basic equations of physics, whatever they may be, cannot indeed decide every arithmetical statement, but whether or not they are complete considered as a description of the physical world, and what completeness might mean in such a case, is not something that the incompleteness theorem tells us anything about.”* In other words, the incompleteness of the arithmetic component of a physical theory need not imply any incompleteness in the description of the physical world.

In Chapter 5 Franzén critically discusses the claims advanced by J. R. Lucas (1961), and updated more recently by Roger Penrose in his *Emperor’s New Mind* (1989) and *Shadows of the Mind* (1994). Lucas argued that no matter how complicated a machine we construct, it will correspond to a formal system, which, in turn, will be subject to a Gödelian construction for finding a formula unprovable in that system. Defending Lucas’ conclusion, Penrose updates the argument in an attempt to show that the aspirations of strong Artificial Intelligence (AI) are doomed to failure, going on to conjecture that a non-computational extension of quantum mechanics will someday provide a theory of consciousness.

Gödel’s own remarks on the subject (in his unpublished 1951 Josiah Willard Gibbs Lecture at Brown University, see vol. III, *Collected Works of Kurt Gödel*, edited by Feferman *et. al.*) are more cautious and nuanced:

\renewcommand\labelitemi{}
::: {.nobullet}
-   The human mind is incapable of formulating (or mechanizing) all its mathematical intuitions. I.e.: If it has succeeded in formulating some of them, this very fact yields new intuitive knowledge, e.g. the consistency of this formalism. This fact may be called the ‘incompletability’ of mathematics. On the other hand, on the basis of what has been proved so far, it remains possible that there may exist (and even be empirically discoverable) a theorem-proving machine which in fact *is* equivalent to mathematical intuition, but cannot be *proved* to be so, nor even proved to yield only *correct* theorems of finitary number theory. The second result is the following disjunction: *Either the human mind surpasses all machines (to be more precise: it can decide more number-theoretic questions than any machine) or else there exist number theoretic questions undecidable for the human mind.*
:::
\renewcommand\labelitemi{\labelitemito}

Criticizing Lucas and Penrose, Franzén argues that “we have no basis for claiming that we (‘the human mind’) can out prove a consistent formal system” because Gödel’s theorem only implies the *equivalence* of the consistency of the formal system and the Gödel statement asserting its own unprovability. In general, however, we have no guarantee that the formal system in question is consistent, an assumption required for us to draw the conclusion there is a truth unprovable in the formal system.

And what about the weaker claim that there could not be any formal system that exactly represents the human mind as far as it ability to prove arithmetical theorems is concerned? Franzén criticizes Hofstader’s reflections to this effect from *Gödel, Escher Bach*, noting Hofstader’s informal remarks have at least “the virtue of making it explicit that the role of the incompleteness theorem is a matter or inspiration rather than implication”:

\renewcommand\labelitemi{}
::: {.nobullet}
-   The other metaphorical analogue to Gödel’s Theorem which I find provocative suggests that ultimately, we cannot understand our own minds/brains…. All the limitative theorems of mathematics and the theory of computation suggest that once your ability to represent your own structure has reached a certain critical point, that is the kiss of death: it guarantees that you can never represent yourself totally.
:::
\renewcommand\labelitemi{\labelitemito}

In such metaphorical statements, Franzén notes, the inability of a formal system to prove its own consistency is interpreted as the inability of the system to “analyze or justify itself, or as a kind of blind spot.” The problem with such a view is that “the metaphor understates the difficulty for a system to prove its own consistency…. \[T\]he unprovability of consistency is really the unassertibility of consistency. A system cannot truly postulate its own consistency, quite apart from questions of analysis and justification, although other systems can truly postulate the consistency of the system (p. 125).”

$$\cdots$$

Franzén’s first two goals were to explain accurately what Gödel’s theorems *do* say to the beginning logic student and to curb the enthusiasm of the non-mathematically inclined who have heard exaggerated claims about the philosophical and mathematical implications of Gödel’s theorem by pointing out what they do *not* say. Gödel’s theorems, as Franzén notes, are stunning and significant enough “without any exaggerated claims for the\[ir\] revolutionary impact.” Franzén’s book will also be of interest to logicians who want a model of sober clarity for explaining the philosophical perspectives opened up by Gödel’s work.

In Chapter 7 Franzén discusses the conceptual connections among Gödel’s Completeness Theorem, non-standard models of arithmetic, and the Incompleteness Theorems. Chapter 8 covers misleading formulations of incompleteness in terms of Kolmogorov-Chaitin complexity. Gregory Chaitin is known for his information-theoretic interpretation of Gödel’s theorem (1965) and for his discovery of the Halting Probability $\Omega$ (also known as Chaitin’s number). As Chaitin touts his results in *The Unknowable* (1999): *“In a nutshell, Gödel discovered incompleteness, Turing discovered uncomputability, and I discovered randomness—that’s the amazing fact that some mathematical statements are true for no reason, they’re true by accident.”* However, Chaitin’s informal explanation that *“… if one has ten pounds of axioms and a twenty-pound theorem, then the theorem cannot be derived from those axioms”* is misleading. In a recent book *Metamath* (2005), Chaitin expands upon this informal account: *“Now we’re really going to get irreducible mathematical facts, mathematical facts that ‘are true for no reason,’ and which simulate in pure math, as much as is possible, independent tosses of a fair coin….”* The problem with Chaitin’s informal explanation, as Franzén points out, is that Chaitin’s version of the Gödel’s theorem does not deal with the complexity of the theorems themselves but instead with theorems that are statements *about* complexity.

There is, moreover, an intriguing connection between Gödel’s incompleteness theorem and axioms of infinity: postulating the existence of various infinite sets has formal consequences for elementary number theory that cannot be proved by elementary means. Most of mathematics done today can be formalized within Zermelo-Fraenkel set theory with the axiom of choice ($\mathrm{ZFC}$). $\mathrm{ZFC}$ minus the axiom of infinity, $\mathrm{ZFC}^{-\omega}$, is equivalent in its arithmetic part, to Peano Arithmetic, and so the Gödel incompleteness theorems apply. Therefore, $\mathrm{ZFC}^{-\omega}$ is incomplete and does not imply its own consistency. It turns out that in $\mathrm{ZFC}$ (which includes the axiom infinity) can prove the consistency of $\mathrm{ZFC}^{-\omega}$. So here we have an example in which adding an axiom of infinity to a theory (in particular, $\mathrm{ZFC}^{-\omega}$) yields new arithmetical theorems (the consistency of $\mathrm{ZFC}^{-\omega}$) not provable within that original theory. Stronger axioms of infinity extending version of $\mathrm{ZFC}$ also yield new arithmetical theorems not provable in the theories they extend. Franzén remarks: “From a philosophical point of view, it is highly significant that extensions of set theory by axioms asserting the existence of very large infinite sets have logical consequences in the realm of arithmetic that are not provable in the theory that they extend.”

As yet, no arithmetical problem of traditional mathematical interest is known to be among the new arithmetical theorems of extensions of $\mathrm{ZFC}$ by axioms of infinity. However, a step in this direction was taken with the Paris-Harrington Theorem (1977). The Paris-Harrington Theorem is related to Ramsey’s theorem, which concerns complete graphs (i.e., graphs where each vertex or “node” is connected with a line or “edge” to all of the other vertices) colored with two colors. According to Ramsey’s theorem, for each pair of positive integers $k$ and $l$ greater than $2$, there exists an integer $R(k, l)$ (known as the *Ramsey number*) such that any graph with $R(k, l)$ nodes whose edges are colored red or green will either have a completely green subgraph of order $k$ or a completely red subgraph of order $l$. For example, at any party with at least six people, there are either three people who are all mutual acquaintances (each one knows the other two) or mutual strangers (each one does not know either of the other two). The Paris-Harrington Theorem, a combinatorial strengthening of Ramsey’s theorem, was the first “natural” statement found to be true but unprovable in Peano Arithmetic.

At the 1930 “Epistemology of the Exact Sciences” Conference in Königsberg, Gödel quietly announced his first incompleteness theorem. Among conference participants were such eminent logicians Rudolf Carnap and Arend Heyting, but only John von Neumann appreciated the profound significance of Gödel’s incompleteness theorem. Not long afterward, von Neumann realized that the second incompleteness theorem could be obtained by formalizing the argument for the first. Communicating his discovery to Gödel in a letter, von Neumann graciously declined to publish when Gödel informed him that this stunning theorem was already discussed in his forthcoming “On Formally Undecidable Propositions in *Principia Mathematica* and Related Systems I” (1931), which would become the most celebrated achievement of 20<sup>th</sup> century logic.

What was Gödel’s Second Incompleteness Theorem and what effect did it has on Hilbert’s program? In addition to constructing the Gödel statement $G$ for the formal system $S$, the argument establishing the implication “if $S$ is consistent, then $G$ is not provable in $S$” could be carried out with S itself.  Moreover, the property of being a Gödel number of a proof in $S$ is a computable one, and so ‘$S$ is consistent’ is a Goldbach-like statement, a statement which if false, can be shown to be false by a computation.  Thus, Gödel’s Second Incompleteness theorem follows: if $S$ proves the statement $\operatorname{Con}(S)$ expressing ‘$S$ is consistent’ in the language of $S$, then $S$ proves $G$, and hence $S$ is in fact inconsistent.  Hilbert’s metamathematical program calling for consistency proofs for formal systems such as arithmetic in which all finitistic arguments can be formalized was effectively dashed by the Second Incompleteness Theorem.

Franzén carefully points out three common misconceptions about the Second Incompleteness Theorem. “First, it is often said that Gödel’s proof shows $G$ to be true, or to be ‘in some sense’ true. But the proof does not show $G$ to be true. What we learn from the proof is that $G$ is true if and only if $S$ is consistent. In this observation, there is no reason to use any such formulation as ‘in some sense true’…” Secondly, Gödel’s theorem does not rule out consistency proofs using methods not formalizable within Peano Arithmetic. Thirdly, “\[a\]nother aspect of the second incompleteness theorem that needs to be emphasized is that it does not show that $S$ can only be proven consistent in a system that is *stronger* than $S$.” For example, Gentzen proved the consistency of Peano Arithmetic ($\mathrm{PA}$) in 1936 by application of an arithmetically expressible instance of transfinite induction up to Cantor’s ordinal $\varepsilon_0$ (the least fixed point under ordinal exponentiation to the base $\omega$), while otherwise using arguments that can be formalized in a very weak subsystem of $\mathrm{PA}$. So the consistency of $\mathrm{PA}$ is proved in a system that is overlaps in part with $\mathrm{PA}$ but is not an extension of it.

On the other hand, it has been argued that if a system $S$ like $\mathrm{PA}$ has been accepted as intuitively true then one ought to accept the consistency statement $\operatorname{Con}(S)$ for $S$. That will give rise to a new formal system $S$' obtained by adjoining $\operatorname{Con}(S)$ to $S$. Now $S$' is also intuitively true, so the process can be iterated, in fact through the constructive transfinite. Alan Turing (1939) showed that one could obtain completeness for Goldbach-like statements for ordinal logics obtained by iterating consistency statements into the constructive transfinite starting with $\mathrm{PA}$. Later, Feferman (1964) showed that one could obtain a progression that is complete for all arithmetical statements by iterating certain reflection principles. Franzén’s other book, *Inexhaustibility: a non-exhaustive treatment* (ASL Lecture Notes in Logic #16, 2004) contains an excellent exposition of the incompleteness theorems and the reader is led step-by-step through the technical details needed to establish a significant part of Feferman’s completeness results for iterated reflection principles for ordinal logics.

Torkel Franzén’s untimely death on April 19, 2006 came shortly before he was to attend, as an invited lecturer, the Gödel Centenary Conference, “Horizons of Truth”, held at the University of Vienna later that month. This, and his invitations to speak at other conferences featuring a tribute to Gödel, testifies to the growing international recognition that he deserved for these works.

***Acknowledgements***: I wish to thank Solomon Feferman for substantive and insightful correspondence during the preparation of this review, Robert Shrock, C. N. Yang Institute for Theoretical Physics, for assistance with \LaTeX to submit my “Gödel Incompleteness, Complexity and Chaos” for the proceedings from the *Kurt Gödel Centenary Symposium* published by the *Collegium Logicum of the Kurt Gödel Society,* and Teresa Spörk-Greenwood for support for my participation in the Gödel Centenary “Horizons of Truth” Conference, University of Vienna, April 28-29<sup>th</sup>, 2006

Gary Mar  
Department of Philosophy  
Stony Brook University  
Stony Brook, New York, USA 11794-3750  
[Gary.Mar\@stonybrook.edu](mailto:Gary.Mar@stonybrook.edu){.email}

